language: c

install:
  - sudo apt-add-repository -y ppa:texlive-backports/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq texlive texlive-latex-extra
  - sudo apt-get install -qq wget aria2 axel curl
  - mkdir -p /tmp/skdoc && cd /tmp/skdoc && wget http://mirror.ctan.org/macros/latex/contrib/skdoc/skdoc.dtx && tex skdoc.dtx && cp skdoc.cls $TRAVIS_BUILD_DIR && cd -

script:
  - make dist
  - make test
