language: c

env:
  global:
    # ctanupload uses these
    - CONTRIBUTION=download
    - NAME="Simon Sigurdhsson"
    - EMAIL="Sigurdhsson@gmail.com"
    - DIRECTORY=/macros/latex/contrib/download
    - LICENSE=free
    - FREEVERSION=lppl

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20160619/texlive.tar.xz | tar -JxC $HOME/texlive

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget aria2 axel curl
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self --all
  - tlmgr install paratype
  - tlmgr install opensans
  - tlmgr install sourcecodepro
  - tlmgr install ly1
  - tlmgr install xindy
  - tlmgr install mweights

script:
  - make dist
  - make test

after_success:
  - ./deploy-ctan.sh download.tar.gz

deploy:
  provider: releases
  api_key:
    secure: Jgu+Q5mnEtWEbGAz/BCVOUM8o5vSowJSby2AUglmyfKEmnef68VdxCeRIjr3h1JJUgdCh7n5zBpQzAa4/MyfpSnhz71t+a+0w23dTv0BgBTPGgpzsSHNupvCVFxzcOVxWWg16LcMnDXwh+peTQsq9+lHySRIvdUPQMfRWH+Naxs=
  file: download.tar.gz
  skip_cleanup: true
  on:
    repo: urdh/download
    tags: true
