language: c

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150408/texlive.tar.xz | tar -JxC $HOME/texlive

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget aria2 axel curl
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr install paratype
  - tlmgr install opensans
  - tlmgr install sourcecodepro
  - tlmgr install ly1

script:
  - make dist
  - make test
