language: c

env:
  global:
    # ctanupload uses these
    - CONTRIBUTION=download
    - NAME="Simon Sigurdhsson"
    - EMAIL="Sigurdhsson@gmail.com"
    - DIRECTORY=/macros/latex/contrib/download
    - DUMMARY="Allow LaTeX to download files using an external process"
    - LICENSE=free
    - FREEVERSION=lppl

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20190725/texlive.tar.xz | tar -JxC $HOME/texlive

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget aria2 axel curl
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self --all
  - tlmgr install paratype
  - tlmgr install opensans
  - tlmgr install sourcecodepro
  - tlmgr install ly1
  - tlmgr install xindy
  - tlmgr install mweights
  - tlmgr remove --force download

script:
  - make dist
  - make test

after_success:
  - ./deploy-ctan.sh download.tar.gz

deploy:
  provider: releases
  api_key:
    secure: nuFb5aJSrU4JiuNr7xz6X+ufwku/RT8NTCD89wfPa15ZOzYqirg1XoGUyD6vt0dKX8QvV2QmPogp9pNZC1rti92MU6R+7iblUl9GQcGLhc6Q8rnxSPQ4UgaHFQXtlNN1dqRPdS0P9nQPghepXEsBUdOJzgJxyQl/fWUhZizR8U8=
  file: download.tar.gz
  skip_cleanup: true
  on:
    repo: urdh/download
    tags: true
