language: c

env:
  global:
    # ctanupload uses these
    - CONTRIBUTION=download
    - NAME="Simon Sigurdhsson"
    - EMAIL="Sigurdhsson@gmail.com"
    - DIRECTORY=/macros/latex/contrib/download
    - DUMMARY="Allow LaTeX to download files using an external process"
    - LICENSE=free
    - FREEVERSION=lppl

before_install:
  - mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20170913/texlive.tar.xz | tar -JxC $HOME/texlive

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wget aria2 axel curl
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - tlmgr update --self --all
  - tlmgr install paratype
  - tlmgr install opensans
  - tlmgr install sourcecodepro
  - tlmgr install ly1
  - tlmgr install xindy
  - tlmgr install mweights
  - tlmgr remove --force download

script:
  - make dist
  - make test

after_success:
  - ./deploy-ctan.sh download.tar.gz

deploy:
  provider: releases
  api_key:
    secure: HkXhNDBorf0aVIVOJJJ7nqOhIUZr6EnnXMjZvYDoWx2Ej4L46z0czstevrcVVDF4S20LCFL3Dcg82FUA7EaWMbl8Tv4l4M7DSqK4iPjT0GxVOde5jBV4ZBe05iBCH38deaeY0F4R9l12UR5r09PN1/zH1I31hUIIDNdm8kRlbpE=
  file: download.tar.gz
  skip_cleanup: true
  on:
    repo: urdh/download
    tags: true
